swagger: "2.0"
info:
  description: |
    Ayden's 2023 onboarding ticket for Confluent
  version: "v1"
  title: "AydenCalculator"

tags:
  - name: Calculator API
    description: Has four operations and an audit endpoint

host: "localhost:8080/calc"
schemes:
  - "http"
paths:
  /add:
    get:
      tags:
        - Add two integers
      summary: |
        Adds two integers
      description: Given two integers, it adds them.
      operationId: add
      parameters:
        - name: number1
          in: query
          required: true
          description: First integer
          type: integer
        - name: number2
          in: query
          required: true
          description: Second integer
          type: integer
      responses:
        '200':
          description: Authenticated
        '404':
          description: Invalid input. Expecting 32-bit integers.
          
  /subtract:  
    get:
      tags:
        - Subtracts two integers
      summary: |
        Subtracts two integers
      description: Given two integers, it subtracts them.
      operationId: subtract
      parameters:
        - name: number1
          in: query
          required: true
          description: First integer
          type: integer
        - name: number2
          in: query
          required: true
          description: Second integer
          type: integer
      responses:
        '200':
          description: Authenticated
        '404':
          description: Invalid input. Expecting 32-bit integers.
          
  /divide:  
    get:
      tags:
        - Divides two integers
      summary: |
        Divides two integers
      description: Given two integers it divides them.
      operationId: divide
      parameters:
        - name: number1
          in: query
          required: true
          description: First integer
          type: integer
        - name: number2
          in: query
          required: true
          description: Second integer
          type: integer
      responses:
        '200':
          description: Authenticated
        '400':
          description: Divide by zero error
        '404':
          description: Invalid input. Expecting 32-bit integers.
          
  /multiply:  
    get:
      tags:
        - Multiplies two integers
      summary: |
        Multiplies two integers together
      description: Given two integers it multiplies them.
      operationId: multiply
      parameters:
        - name: number1
          in: query
          required: true
          description: First integer
          type: integer
        - name: number2
          in: query
          required: true
          description: Second integer
          type: integer
      responses:
        '200':
          description: Authenticated
        '404':
          description: Invalid input. Expecting 32-bit integers.
          
  /audit:  
    get:
      tags:
        - Get audit log
      summary: |
        Gets audit log of calculator operation history
      operationId: audit
      responses:
        '200':
          description: Authenticated
        '401':
          description: Unauthorized
  
  